spring.application.name=safeguard
server.port=${PORT:8080}

spring.mongodb.uri=${MONGODB_URI}

disaster.api.hospital.baseUrl=https://apis.data.go.kr

disaster.api.hospital.serviceKey=${SAFEMAP_API_KEY:}

disaster.api.shelter.civil-defense.service-key=${SAFEMAP_API_KEY:}
disaster.api.shelter.earthquake.service-key=${SAFEMAP_API_KEY:}
disaster.api.shelter.tsunami.service-key=${SAFEMAP_API_KEY:}

